### ISSUE TITLE
Warning and error messages when using lorenzFilter, ScannobyGtf and deDetection functions

### ISSUE THREAD

**Issue by fionasguo** [kendomaniac/rCASC#1]
Hi,
I am following the exact steps in this documentation to learn to use the rCASC package, with the example data from Buettner. 
https://link.springer.com/content/pdf/10.1007%2F978-1-4939-9240-9_25.pdf

However, when I was trying to use the function lorenzFilter, I got a warning message:
Warning: X is not an integer. Confidence intervals are computed using a formula suitable for integer values of X and N.

In addition, when I used scannobyGtf and deDetection functions, this error message showed up in both functions:
sh: 1: Syntax error: Bad fd number

The functions did produce some results, but the results are obviously not correct, compared to the results shown in the example document. I don't know why these are coming up. Could I get some help with these? Thank you a ton!

Best
Fiona

**Comment by kendomaniac** [comment]
Hi Fiona,
could please download the latest version of rCASC:
library(devtools)
install_github("kendomaniac/rCASC", ref="master")

then could please try the following example:
library(rCASC)
     system("unzip testSCumi_mm10.csv.zip")
     #filtering low quality cells
     lorenzFilter(group="docker",scratch.folder="/data/scratch/",
                  file=paste(getwd(),"testSCumi_mm10.csv",sep="/"),
                  p_value=0.05,separator=',')

I tested it and I do not get any error.
The result is the filtered table called lorenz_testSCumi_mm10.csv 782 cells out of 805 present in the testSCumi_mm10.csv 

the error: sh: 1: Syntax error: Bad fd number is due to a syntax problem in some linux version, we are fixing it but it does not affect results 
https://unix.stackexchange.com/questions/407798/syntax-error-bad-fd-number

Referring to the example in https://link.springer.com/content/pdf/10.1007%2F978-1-4939-9240-9_25.pdf
since I do not have access to the book could please send me the code you are referring for the example that provides errors?
As soon I get the code you used, I will check.

Could please tell me which operating system and  RAM on your PC?
Cheers
Raf

**Comment by fionasguo** [comment]
Hi Raf,

Thank you for the reply!

I tried your example code with testSCumi_mm10.csv. and tried the example code I mentioned (it is also on this page: https://rdrr.io/github/kendomaniac/rCASC/man/deDetection.html). They both work out now! I don't know what was wrong before but I think I'm getting the correct results currently. I still want to let you know the warning messages I received, just in case it is something important:

Here is the example code I was working on:

    system("wget http://130.192.119.59/public/buettner_counts_noSymb.txt.zip")
    unzip("buettner_counts_noSymb.txt.zip")
    lorenzFilter(group="docker", scratch.folder="/data/scratch/",
                data.folder=getwd(), matrixName="buettner_counts_noSymb",
                p_value=0.05, format="txt", separator='\t')

    system("wget ftp://ftp.ensembl.org/pub/release-92/gtf/mus_musculus/Mus_musculus.GRCm38.92.gtf.gz")
    system("gzip -d Mus_musculus.GRCm38.92.gtf.gz")
    scannobyGtf(group="docker", data.folder=getwd(),
                 counts.table="lorenz_buettner_counts_noSymb.txt",
                 gtf.name="Mus_musculus.GRCm38.92.gtf",
                 biotype="protein_coding", mt=FALSE, ribo.proteins=FALSE,
                 file.type="txt", umiXgene=3)

    deDetection(group="docker", data.folder=getwd(),
               counts.table="annotated_lorenz_buettner_counts_noSymb.txt",
               file.type="txt", logFC.threshold=1, FDR.threshold=0.05, logCPM.threshold=4, plot=TRUE)

1. When running this lorenzFilter function, I got:

Warning: x is not an integer. confidence intervals are computed using a formula suitable for integer values of x and n.

**Comment by kendomaniac** [comment]
Can you please send me the dataset that produces this warming?
Is it smartseq or 10xgenomics data?
